### ISSUE TITLE
Proxy Over quota

### ISSUE THREAD

**Issue by mattazwebdesign** [Cipher-Coder/devTabs#1]
GitHub Graph is not getting info. Just blank. In console it shows error. Traced back it looks like the proxy used to pull the data from GitHub site is going over its quota.

**Comment by Cipher-Coder** [comment]
This was a problem with one of the libraries I used for the calendar. I have fixed the issue with the proxy in the lib by creating my own proxy using Google App Engine and I have updated the repo as well as the Chrome and Firefox versions. Make sure you update your extensions and this will go away. The version you should be on is v 0.2.4.
